# Generated by Django 3.2.3 on 2024-08-12 18:10

from django.db import migrations, models

import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[recipes.validators.cooking_time_validator], verbose_name='Время приготовления'),
        ),
    ]
