# Generated by Django 3.2.3 on 2024-08-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20240816_1547'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='нельзя добавить один и тот же рецепт в корзину дважды'),
        ),
        migrations.AddConstraint(
            model_name='userrecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='нельзя добавить один и тот же рецепт в избранное дважды'),
        ),
    ]
