# Generated by Django 3.2.3 on 2024-08-12 18:10

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_foodgramuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodgramuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[users.validators.username_validator]),
        ),
    ]
