# Generated by Django 3.2.3 on 2024-08-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_foodgramuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ('email',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
